### ISSUE TITLE
gyre_in_mesa makefile problem

### ISSUE THREAD

**Issue by evbauer** [wmwolf/mesa_cli#1]
Ok, so this is kinda my fault, but I wanted to give you a heads up about something coming down the pipeline. The gyre_in_mesa test case I just committed has a custom makefile with the line

`WORK_DIR = ..`

The command  `mesa test gyre_in_mesa` kills this line in its zeal for getting rid of the test suite's "../../../.." stuff, and the result is that gyre_in_mesa won't compile when using the mesa test command.

The standard makefile hides almost everything behind an include command, so I guess that's why you wouldn't have run across this before...

**Comment by wmwolf** [comment]
Yuck.

Should we then just put in a stupid hack to protect against this specific case, or is it woth building an infrastructure to discriminate between "good" and "bad" variable naming? I guess we just really need to kill off MESA_DIR most of the time, don't we?

**Comment by evbauer** [comment]
Yeah, I think MESA_DIR is really what always needs to be killed, and other relative paths are likely to need to stay around.

**Comment by wmwolf** [comment]
Lazy compromise:

Right now anything with ".." is deleted. Could I just change that to "../.."? There are (or at least were) some test cases that set up references in the local MESA tree that don't make sense out side of the test_suite directory.

Any reasonable makefile should not be accessing anything more than one directory up its tree, right?

**Comment by wmwolf** [comment]
Plus then I get to include this stupid line of code:

```ruby
make_lines.reject! { |line| line =~ /\.\.\/\.\./ }
```

**Comment by wmwolf** [comment]
Version 0.1.7 is out with this fix. Give it a spin and close this issue out if it fixes the problem.

**Comment by evbauer** [comment]
Yes, I think that's perfect. The problem is that the `mk` script cd's into the `make` directory. So it needs to know about one level of `..` to get back into the work directory and see the `src` directory. Any level higher than that refers to the MESA tree and makes no sense outside the test_suite.

**Comment by evbauer** [comment]
Yep. Latest update works like magic. Thanks!
